# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "ci-test" ]
  pull_request:
    branches: [ "ci-test" ]

jobs:
  lint-validation:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: yarn install
    - run: /home/shajahan/simplogics/momcicd/build_scripts/copy_build.sh $(pwd)
