# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "ci-test" ]
  pull_request:
    branches: [ "ci-test" ]
env:
  NAME: shajahan up
  VERSION: 1.0

jobs:
  lint-validation:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: /home/shajahan/simplogics/momcicd/build_scripts/copy_build.sh "$NAME$VERSION"
